[versions]
kotlin = "1.8.0"
androidGradle = "8.0.2"

[libraries]
coreKtx = { module = "androidx.core:core-ktx", version = "1.8.0" }
appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
material = { module = "com.google.android.material:material", version = "1.9.0" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
jUnit = { module = "junit:junit", version = "4.13.2" }
androidJUnit = { module = "androidx.test.ext:junit", version = "1.1.5" }
espresso = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradle" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradle" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }