[versions]
kotlin = "1.8.0"
androidGradle = "8.0.2"
lifecycle = "2.6.1"
hilt = "2.46.1"

[libraries]
coreKtx = { module = "androidx.core:core-ktx", version = "1.8.0" }
appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
viewModelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycleKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
fragmentKtx = { module = "androidx.fragment:fragment-ktx", version = "1.5.7" }
material = { module = "com.google.android.material:material", version = "1.9.0" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
recyclerView = { module = "androidx.recyclerview:recyclerview", version = "1.2.1" }
viewBindingKtx = { module = "com.wada811.viewbindingktx:viewbindingktx", version = "3.0.0" }
persianDate = { module = "com.github.samanzamani:PersianDate", version = "1.6.1" }
shimmer = { module = "com.facebook.shimmer:shimmer", version = "0.5.0" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltCompiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
jUnit = { module = "junit:junit", version = "4.13.2" }
androidJUnit = { module = "androidx.test.ext:junit", version = "1.1.5" }
espresso = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradle" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradle" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }